server:
  port: ${server.port}
logging:
  file: mall-web-manage-${spring.profiles.active}.log
  level:
    org.springframework.web: INFO
#    com.mall.dao.mapper: debug #打印sql
spring:
  application:
    name: mall-web-manage
    group: com.wjz.mall
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 20MB
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.mall.dao.entity.*
#  驼峰转换
  configuration:
    map-underscore-to-camel-case: true
aliyun:
  accessKeyId: ${aliyun.accessKeyId}
  accessKeySecret: ${aliyun.accessKeySecret}
  oss:
    endpoint: http://oss-cn-beijing.aliyuncs.com
    bucketName: wjz-mall-image
    urlPrefix: https://wjz-mall-image.oss-cn-beijing.aliyuncs.com/
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 配置swagger
swagger:
  title: 碧直播APP接口API
  version: 1.0
  base-package: com.mall
  authorization:
    key-name: Authorization


