alibaba:
  acm:
    endpoint: acm.aliyun.com
    namespace: c9816879-f0f8-4501-b8dd-f51715db5210
    accessKey: LTAI4FjhAeZusCt8fySLxnwh
    secretKey: nSuTUrtUK6QuDOZTzrMGafnSO3KMia
    group: com.wjz.mall
    file-extension: properties
