server:
  servlet:
    session:
      timeout: 72000s
spring:
  datasource:
    url: jdbc:mysql://47.110.47.162:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect
  devtools:
    restart:
      enabled: true
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  profiles:
    active: dev


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.mall.malladmin.entity.*
#  驼峰转换
  configuration:
    map-underscore-to-camel-case: true
